/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import javax.swing.Timer;

/**
 *
 * @author Dani
 */
public class VentanaJuego extends javax.swing.JFrame {
    
    int anchoPantalla = 600;
    int altoPantalla = 450;  
    
    BufferedImage buffer = null;
    
    //declaro un objeto de tipo nave
    Nave miNave = new Nave(anchoPantalla);
    //declaro dos variables booleanas que controlen el movimiento de la nave
     boolean pulsadaDerecha = false;
      boolean pulsadaIzquierda = false;
    
    Timer temporizador = new Timer(10, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e){
    bucleDelJuego();
        }
     });
    
    
    
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
        
        //cambiamos las dimensiones de la ventana
        this.setSize(anchoPantalla+13, altoPantalla+47);
        
        //creamos el buffer a partir del jpanel
        buffer=(BufferedImage) jPanel1.createImage(anchoPantalla, altoPantalla);
        buffer.createGraphics();
        
        //inicio el juego
        temporizador.start();
        
        //posiciona la nave abajo del todo
        miNave.setX(anchoPantalla/2);
        miNave.setY(altoPantalla - miNave.imagenNave.getHeight(null));
        
    }
    
    private void bucleDelJuego(){
        //apunto al buffer
    Graphics g2 = (Graphics2D) buffer.getGraphics();
    
    
        //pinto un rectangulo negro del tamaño de la ventana
        g2.setColor(Color.BLACK);
        g2.fillRect(0, 0, anchoPantalla, altoPantalla);
        
        ////////////////////////////////////////////////////////
        /////////CODIGO DEL JUEGO ///////////////////////////
        if(pulsadaIzquierda){
            miNave.setX(miNave.getX() - 1);
        }
        if(pulsadaDerecha){
            miNave.setX(miNave.getX() + 1);
        }
        
        g2.drawImage(miNave.imagenNave, miNave.getX(), miNave.getY(), null);
        
        
        //////////////////////////////////////////////////////
        
           g2=(Graphics2D)jPanel1.getGraphics();
           g2.drawImage(buffer,0,0,null);
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_LEFT){
      pulsadaIzquierda = true;
      pulsadaDerecha = false;
      }
      
      if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
      pulsadaIzquierda = false;
      pulsadaDerecha = true;
      }
     
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       pulsadaIzquierda = false;
      pulsadaDerecha = false;
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
